In [3]:
# for generate, preprocessing data
import numpy as np
from sklearn import preprocessing

In [7]:
# Create sample data
# Use array 2 dimensi
sample_data = np.array(
    [[2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [0.5, -7.9, 5.6],
    [5.9, 2.3, -5.8]]
)

In [13]:
print("Dataset : \n",sample_data)
# untuk melihat dimensi
print("Dimensi : ",sample_data.shape)

Dataset : 
 [[ 2.1 -1.9  5.5]
 [-1.5  2.4  3.5]
 [ 0.5 -7.9  5.6]
 [ 5.9  2.3 -5.8]]
Dimensi :  (4, 3)


In [16]:
'''
Binarisation. technic for data preprocessing
parameter threshold untuk batasan.
jika nilai lebih besar dari 0.5 maka akan jadi 1, dan sebaliknya
'''
preprocessor = preprocessing.Binarizer(threshold=0.5)
# change value sample_data to binarisation
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

In [19]:
'''
Scaling. technic for data preprocessing
Brtujuan untuk menghasilkan data numerik yg berada
dlm skala tertentu
parameter feature_range di berikan value data tuple,
index pertama adalah skala terkecil, index kedua skala terbesar
Note : inget pljaran skala pas sd kelas 6:)
'''
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

In [22]:
'''
Normalisation.  technic for data preprocessing
Bertujuan untuk normalisasi terhadap data numerik
parameter pertama di berikan value data yg akan di
normalisasi, parameter kedua di beri value string l1
yang akan menerapkan list absolute definiton
'''
# Contoh normalisasi l1
l1_normalize_data = preprocessing.normalize(sample_data, norm='l1')
# Contoh normalisasi l2
l2_normalize_data = preprocessing.normalize(sample_data, norm='l2')
print("l1\n",l1_normalize_data)
print("l2\n",l2_normalize_data)

l1
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]
l2
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]
